---
title: "R Notebook"
output: html_notebook
---

```{r}
library(JASPAR2020)
library(TFBSTools)
library(BSgenome.Mmusculus.UCSC.mm10)
library(patchwork)
set.seed(1234)
```

```{r}
fib <- readRDS("./fib1418_macs.rds")
```

```{r}
getSeq(BSgenome.Mmusculus.UCSC.mm10,granges(fib))
```

```{r}
DefaultAssay(fib)<-'ATAC'
gr <- granges(fib)
seq_keep <- seqnames(gr) %in% seqnames(BSgenome.Mmusculus.UCSC.mm10) 
seq_keep <- as.vector(seq_keep)
feat.keep <- GRangesToString(grange = gr[seq_keep])
fib[["ATAC"]] <- subset(fib[["ATAC"]], features = feat.keep)
```



```{r}
pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
)

# add motif information
fib <- AddMotifs(
  object = fib,
  genome = BSgenome.Mmusculus.UCSC.mm10,
  pfm = pfm
)
```

```{r}
enriched.motifs.dp <- FindMotifs(
  object = fib,
  features = dp$query_region
)
enriched.motifs.ad <- FindMotifs(
  object = fib,
  features = adipo$query_region
)
```


```{r}
MotifPlot(
  object = fib,
  motifs = head(rownames(enriched.motifs.dp))
)

MotifPlot(
  object = fib,
  motifs = head(rownames(enriched.motifs.ad))
)
```